
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 */

/**
 *
 * @author urksi
 */
public class InsertarArticulo extends javax.swing.JFrame {

    /**
     * Creates new form InsertarArticulo
     */
    DBC artDriver = new DBC();
    public InsertarArticulo() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Antes de continuar verifica tener un ID Partida y una Clave de Recurso");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FieldNo_Serie = new javax.swing.JTextField();
        FieldModelo = new javax.swing.JTextField();
        FieldMarca = new javax.swing.JTextField();
        FieldResguardo = new javax.swing.JTextField();
        FieldNombre = new javax.swing.JTextField();
        FieldPatrimonio = new javax.swing.JTextField();
        FieldACompra = new javax.swing.JTextField();
        FieldNota = new javax.swing.JTextField();
        FieldFactura = new javax.swing.JTextField();
        FieldCostoActual = new javax.swing.JTextField();
        FieldPrecio_Fac = new javax.swing.JTextField();
        FieldStatus = new javax.swing.JTextField();
        FieldAVida = new javax.swing.JTextField();
        FieldCaracteristicas = new javax.swing.JTextField();
        FieldProveedor = new javax.swing.JTextField();
        FieldClaveRecurso = new javax.swing.JTextField();
        FieldBien = new javax.swing.JTextField();
        FieldPartida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("No_Serie:  ");

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("No. Resguardo");

        jLabel6.setText("Nota:");

        jLabel7.setText("No. Patrimonio");

        jLabel8.setText("A. Compra");

        jLabel9.setText("No_Factura");

        jLabel10.setText("Precio_Fac");

        jLabel11.setText("Costo Act:");

        jLabel12.setText("Status:");

        jLabel13.setText("A. Vida:");

        jLabel14.setText("Caracteristicas:");

        jLabel15.setText("Clave Recurso:");

        jLabel16.setText("Id. Partida");

        jLabel17.setText("Proveedor:");

        jLabel18.setText("Tipo Bien:");

        FieldNo_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNo_SerieActionPerformed(evt);
            }
        });

        FieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldModeloActionPerformed(evt);
            }
        });

        FieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMarcaActionPerformed(evt);
            }
        });

        FieldResguardo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldResguardoActionPerformed(evt);
            }
        });

        FieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombreActionPerformed(evt);
            }
        });

        FieldPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPatrimonioActionPerformed(evt);
            }
        });

        FieldACompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldACompraActionPerformed(evt);
            }
        });

        FieldNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNotaActionPerformed(evt);
            }
        });

        FieldFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldFacturaActionPerformed(evt);
            }
        });

        FieldCostoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCostoActualActionPerformed(evt);
            }
        });

        FieldPrecio_Fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPrecio_FacActionPerformed(evt);
            }
        });

        FieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldStatusActionPerformed(evt);
            }
        });

        FieldAVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldAVidaActionPerformed(evt);
            }
        });

        FieldCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCaracteristicasActionPerformed(evt);
            }
        });

        FieldProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldProveedorActionPerformed(evt);
            }
        });

        FieldClaveRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldClaveRecursoActionPerformed(evt);
            }
        });

        FieldBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBienActionPerformed(evt);
            }
        });

        FieldPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPartidaActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldACompra, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(FieldNota)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(FieldFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FieldResguardo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FieldModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FieldNo_Serie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FieldPatrimonio))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(FieldPrecio_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(FieldBien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(FieldCostoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(FieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(FieldAVida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(FieldClaveRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(FieldCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FieldNo_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(FieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(FieldResguardo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(FieldPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldACompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldPrecio_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldCostoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(FieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(FieldAVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(FieldCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(FieldClaveRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(FieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(FieldPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNo_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNo_SerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNo_SerieActionPerformed

    private void FieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldModeloActionPerformed

    private void FieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMarcaActionPerformed

    private void FieldResguardoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldResguardoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldResguardoActionPerformed

    private void FieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombreActionPerformed

    private void FieldPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPatrimonioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPatrimonioActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void FieldACompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldACompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldACompraActionPerformed

    private void FieldNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNotaActionPerformed

    private void FieldFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldFacturaActionPerformed

    private void FieldCostoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCostoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCostoActualActionPerformed

    private void FieldPrecio_FacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPrecio_FacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPrecio_FacActionPerformed

    private void FieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldStatusActionPerformed

    private void FieldAVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldAVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldAVidaActionPerformed

    private void FieldCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCaracteristicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCaracteristicasActionPerformed

    private void FieldProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldProveedorActionPerformed

    private void FieldClaveRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldClaveRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldClaveRecursoActionPerformed

    private void FieldBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBienActionPerformed

    private void FieldPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPartidaActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        insertarArticulo();
    }//GEN-LAST:event_jButton1MousePressed
    public void insertarArticulo(){
        artDriver.init();
        
        String no_serie = FieldNo_Serie.getText();
        String marca = FieldMarca.getText();
        String modelo = FieldModelo.getText();
        String nombre = FieldNombre.getText();
        String no_resguardo = FieldResguardo.getText();
        String no_patrimonio = FieldPatrimonio.getText();
        String nota = FieldNota.getText();
        int a_compra = Integer.parseInt(FieldACompra.getText());
        String no_factura = FieldFactura.getText();
        int precio_fac = Integer.parseInt(FieldPrecio_Fac.getText());
        int costo_act = Integer.parseInt(FieldCostoActual.getText());
        String status = FieldStatus.getText();
        int a_vida = Integer.parseInt(FieldAVida.getText());
        String caracteristicas = FieldCaracteristicas.getText();
        int cla_recurso = Integer.parseInt(FieldClaveRecurso.getText());
        String proveedor = FieldProveedor.getText();
        int id_partida = Integer.parseInt(FieldPartida.getText()); 
        String tipo_bien = FieldBien.getText();
        String nombre_recurso, nom_partida;
        artDriver.createStatement();
        int opt = JOptionPane.showConfirmDialog(null, "La clave de recurso se encuentra registrada?");
        switch (opt){
            
            case 1:
                nombre_recurso = JOptionPane.showInputDialog(null, "Ingresa nombre del recurso");
                artDriver.update("insert into inventario_recurso (cla_recurso, nombre) values ('"+cla_recurso+"', '"+nombre_recurso+"')");
                break;
            default:
                break;
        
        }
        opt = JOptionPane.showConfirmDialog(null, "El ID de partida se encuentra registrado?");
        switch (opt){
            
            case 1:
                nom_partida = JOptionPane.showInputDialog(null, "Ingresa el nombre de partida");
                artDriver.update("insert into inventario_partidas (id_partida, nom_partida) values ('"+id_partida+"', '"+nom_partida+"')");
                break;
            default:
                break;
        
        }
        String sqlOrder = "insert into inventario_articulos (cla_recurso, id_partida, no_serie, marca, modelo, nombre, no_resguardo, no_patrimonio, nota, a_compra, no_fatura, precio_fac, costo_act, status, a_vida, caracteristicas, proveedor, tipo_bien) values ("
                +"'"+cla_recurso+"', '"+id_partida+"', '"+no_serie+"', '"+marca+"', '"+modelo+"', '"+nombre+"', '"+no_resguardo+"', '"+no_patrimonio+"', '"+nota+"', '"+a_compra+"', '"+no_factura+"', '"+precio_fac+"', '"+costo_act+"', '"+status+"', '"+a_vida+"', '"+caracteristicas+"', '"+proveedor+"', '"+tipo_bien+"')";
        System.out.println(sqlOrder);
        artDriver.update(sqlOrder);
        
        artDriver.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldACompra;
    private javax.swing.JTextField FieldAVida;
    private javax.swing.JTextField FieldBien;
    private javax.swing.JTextField FieldCaracteristicas;
    private javax.swing.JTextField FieldClaveRecurso;
    private javax.swing.JTextField FieldCostoActual;
    private javax.swing.JTextField FieldFactura;
    private javax.swing.JTextField FieldMarca;
    private javax.swing.JTextField FieldModelo;
    private javax.swing.JTextField FieldNo_Serie;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldNota;
    private javax.swing.JTextField FieldPartida;
    private javax.swing.JTextField FieldPatrimonio;
    private javax.swing.JTextField FieldPrecio_Fac;
    private javax.swing.JTextField FieldProveedor;
    private javax.swing.JTextField FieldResguardo;
    private javax.swing.JTextField FieldStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
